name: gameanalytics_sdk
description: Official Flutter SDK for GameAnalytics. GameAnalytics is a free analytics platform that helps game developers understand their players' behaviour by delivering relevant insights.
version: 1.2.0
homepage: https://gameanalytics.com
repository: https://github.com/GameAnalytics/GA-SDK-FLUTTER
documentation: https://gameanalytics.com/docs/s/article/Flutter-SDK-Setup
issue_tracker: https://github.com/GameAnalytics/GA-SDK-FLUTTER/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gameanalytics.sdk.flutter
        pluginClass: GameAnalyticsPlugin
      ios:
        pluginClass: GameAnalyticsPlugin
      web:
        pluginClass: GameAnalyticsWeb
        fileName: web/gameanalytics_web.dart
